package com.app.zovent.utils

object Constants {
    const val KEY: String = "passwordpassword"
    const val NOTIFICATION: String = "Notification"
    const val HELPCENTERFRAGMENT: String = "HelpCenterFragment"
    val ASKCREDITFRASGMENT = "AskCreditfragment"
    var PRIVACYANDPOLICY: String = "PrivacyAndPolicy"
    var TERMANDCONDITION = "TermsAndCondition"
    val MYQRCODEFRAGMENT: String = "MyQrCodeFragment"
    val HOMEFRAGMENT: String = "HomeFragment"
    var FRAGMENTNAME = "fragmentName"
    var CREATEPIN = "Create Pin"
    var CONFIRMPIN = "Confirm Pin"
    var ScreenTitleName = "ScreenTitleName"
    var VERIFICATIONCODEFRAGMENT = "verificationCodeFragment"
    var CREATEPINFRAGMENT = "CreatePinFragment"
    var PROFILESETTINGFRAGMENT = "ProfileSettingFragment"
    var SPLASHFRAGMENT = "SplashFragment"
    var LOGOUTFRAG = "LogoutFragment"
    var SELECTLANGUAGEFRAG = "SelectLanguageFragment"
    var CONTEXT = "context"
    const val TOKEN = "token"
    var CALLBACK = "callback"
    var PINDATA = "pindata"
    var MPIN = "mpin"
    var WRONGPIN = "wrong pin"
    var MPINVERIFICATIONFRASGMENT = "mpinVerificationFragment"
    var ISPINCREATED = "ispinCreated"
    var DATA = "data"
    var AMOUNT = "amount"
    var INVOICE = "invoice"
}